### ISSUE TITLE
deploying open PRs to staging only

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#1581]
Now that we are on GitHub actions and we have action-experts like @sgibson91 and @hamelsmu, I wonder if we can feasibly have *test* deployments, where we deploy an open PR **to staging only**. I'm not sure what the right mechanism for that would be, but it seems like it might be possible with the controls we have.

The idea would be that a special comment or tag (or some other trigger) could be used on a PR to deploy it to staging without also deploying to production. We would need to still limit the deployment permissions to those who can merge PRs (i.e. not anyone can open a PR and comment on their own PR to deploy to staging).

I'm sure we could do it by merging to a `staging` branch, but I think it would be cool if we could accomplish it without needing to create that extra branch.

Does this sound doable?

**Comment by sgibson91** [comment]
I think this would only take a few edits to the `cd.yml` workflow. If we add the `pull_request` trigger then we can use conditionals to run the 2 jobs for different triggers. Checkout [this action](https://github.com/alan-turing-institute/the-turing-way/blob/master/.github/workflows/lorem-ipsums.yml) I wrote for the Turing way, which only tests changed files in a Pull Request and then tests _all_ files on merge to master. (The `if` statements are the important bit and we'd want to define them at the job level, not the step level.)

**Comment by sgibson91** [comment]
Another thing to consider is **when** the PR is opened and what effect this has on the state of staging. I'm one of those people who opens PRs early and keeps pushing to them so I can continually check CI is passing. The GHA config I'm suggesting will re-run tests on every commit to an open PR. So if one commit breaks staging, how can we gracefully recover? We may want to restrict the `pull_request` trigger to certain events, such as `opened` only? Or it might just be people like me needing to learn a different workflow 😄

**Comment by sgibson91** [comment]
> We would need to still limit the deployment permissions to those who can merge PRs (i.e. not anyone can open a PR and comment on their own PR to deploy to staging).

This section has just sunk into my post-holiday brain. This will be trickier. I'll mull it over but it _could_ involve checking if `github.actor` is in a list of allowed mergers.

**Comment by hamelsmu** [comment]
Another flexible way, rather than maintaining a whitelisted names, is to inspect the payload via the `github.event` variable.  This contains the commiters permission level on the repo.  I am doing something similar in fastpages:

```yaml
   - name: Comment on issue if sufficient access does not exist
      if: |
        (github.event.issue.author_association != 'OWNER') && 
        (github.event.issue.author_association != 'COLLABORATOR') &&
        (github.event.issue.author_association != 'MEMBER')
      uses: actions/github-script@0.6.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var permission_level = process.env.permission_level;
          var url = 'https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account'
          var msg = `You must have the [permission level](${url}) of either an **OWNER**, **COLLABORATOR** or **MEMBER** to instantiate an upgrade request.  Your permission level is ${permission_level}`
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: msg
          })
          github.issues.update({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed'
          })
          throw msg;
      env:
        permission_level: ${{ github.event.issue.author_association }}
```
