### ISSUE TITLE
Failed to connect to event stream. RuntimeError: No space left on device: 'cache'

### ISSUE THREAD

**Issue by mohsen-gis** [jupyterhub/mybinder.org-deploy#2229]

**Comment by consideRatio** [comment]
This is not for the docker image build pod as you had an error at, but ~7 pods on turing.mybinder.org had the following issues recently. So, could be a related reason.

```
status:
  message: 'The node was low on resource: ephemeral-storage. Container notebook was
    using 252Ki, which exceeds its request of 0. '
  phase: Failed
  reason: Evicted
  startTime: "2022-05-29T20:25:10Z"
```
