### ISSUE TITLE
Binderhub metrics not showing in grafana

### ISSUE THREAD

**Issue by Choogster1** [jupyterhub/mybinder.org-deploy#2412]
Hi there. I'm trying to get binderhub dashboards working in grafana, the prometheus grafana stack, but none of the metrics appear when I try creating a dashboard - I enter 'binderhub' in the query box and none of the metrics that should be there show up.

Is there some kind of setting I should be using to expose the metrics when I deploy the binderhub helm chart to get them to appear in grafana?

Thanks

**Comment by rgaiacs** [comment]
Dear @Choogster1,

did you try

```
binderhub:
  service:
    annotations:
      "prometheus.io/scrape": "true"
      "prometheus.io/port": "8585"
      "prometheus.io/path": "/binder/metrics"
```

I'm closing this as it is similar to https://github.com/jupyterhub/mybinder.org-deploy/issues/2585. Feel free to reopen the issue.
