### ISSUE TITLE
Activate pod-priority & user-placeholders in z2jh!

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#812]
After #811 is closed, we could enable pod priority and user-placeholers in z2jh, with about 10 user placeholders users, the actual users arriving would in general not need to await the time it takes to start up a new node - because that has already been done 10 users ahead of time! So, if the influx of users is steady and linear, and 10 new users will arrive at the time it takes to scale up a new node for the cluster-autoscaler, then by using 10 user placeholders no real users would ever need to await the scale up event.

The functionality was implemented in the following z2jh PRs:
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/928
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/929

To activate the stuff, do something like this:

```yaml
scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 10
```
